service:
  version: "1.0.0"
  host: "0.0.0.0"
  port: 8006
  history_retention_days: 30

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "dbpassword"
  database: "postgres"
  pool:
    min_size: 2
    max_size: 10
    command_timeout: 60.0
