version: "1.0.0"

hardware:
  # 1. Network Configuration
  network:
    plc:
      address: "192.168.0.130"
      tag_file: "resources/tags/MicroColdSpray_basic.csv"  # Required by productivity library
      polling_interval: 1.0
      timeout: 5.0
      retry:
        max_attempts: 3
        delay: 1.0
    ssh:
      host: "192.168.0.200"
      port: 22
      username: "root"
      password: "deltatau"
      timeout: 5.0
      command_timeout: 2.0
      retry:
        max_attempts: 3
        delay: 5.0
    connection:  # Global connection settings
      timeout: 30.0  # Overall connection timeout

  # 2. Physical Configuration
  physical:
    hardware_sets:
      set1:
        nozzle: "nozzle1"
        feeder: "feeder1"
        deagglomerator: "deagg1"
        offset_x: 0.0
      set2:
        nozzle: "nozzle2"
        feeder: "feeder2"
        deagglomerator: "deagg2"
        offset_x: 38.1
    
    stage:
      dimensions:
        x: 200.0  # mm total travel
        y: 200.0  # mm total travel
        z: 40.0   # mm total travel
      home:
        x: 0.0    # Corner position
        y: 0.0    # Corner position
        z: 0.0    # Fully down (away from nozzle)
    
    substrate_holder:
      dimensions:
        total:
          width: 158.14   # mm (full holder width)
          height: 158.14  # mm (full holder height)
        sprayable:
          width: 141.0    # mm (sprayable area)
          height: 141.0   # mm (sprayable area)
        trough:
          width: 132.74   # mm (trough width)
          offset_y: 16.51 # mm (from bottom edge)
          height: 25.40   # mm (trough section height)
    
    nozzles:
      nozzle1_offset_x: 0.0
      nozzle2_offset_x: 38.1  # 1.5 inch offset
      common_y: 100.0

  # 3. Motion Control
  motion:
    limits:
      x:
        travel: [0.0, 200.0]  # mm, from corner
        velocity:
          max: 100.0    # mm/s
          default: 50.0  # mm/s
          jog:
            fast: 50.0   # mm/s
            slow: 10.0   # mm/s
        acceleration:
          max: 250.0    # mm/s²
          default: 100.0  # mm/s²
          jog: 50.0     # mm/s²
      
      y:
        travel: [0.0, 200.0]  # mm, from corner
        velocity:
          max: 100.0    # mm/s
          default: 50.0  # mm/s
          jog:
            fast: 50.0   # mm/s
            slow: 10.0   # mm/s
        acceleration:
          max: 250.0    # mm/s²
          default: 100.0  # mm/s²
          jog: 50.0     # mm/s²
      
      z:
        travel: [0.0, 40.0]  # mm, from home (0=away from nozzle)
        velocity:
          max: 50.0     # mm/s
          default: 10.0  # mm/s
          jog:
            fast: 15.0   # mm/s
            slow: 5.0    # mm/s
        acceleration:
          max: 100.0     # mm/s²
          default: 50.0  # mm/s²
          jog: 25.0     # mm/s²

  # 4. Safety Systems
  safety:
    position:
      tolerance: 0.1  # mm
      verification_interval: 1.0  # seconds
    
    motion:
      velocity_check: true
      acceleration_check: true
      limit_check: true
      require_safe_z_for_xy: true

    gas:
      main_pressure:
        min: 70.0  # PSI - minimum for safe operation
        warning: 80.0  # PSI - warning threshold
        error: 60.0  # PSI - emergency stop threshold
      regulator_pressure:
        min: 40.0  # PSI - minimum for powder transport
        max: 80.0  # PSI - maximum for nozzle safety
      feeder_pressure:
        min: 5.0  # PSI - minimum for powder flow
        max: 20.0  # PSI - maximum for powder control