hardware:
  network:
    connection:
      timeout: 30.0
    plc:
      address: "192.168.0.130"
      tag_file: "resources/tags/MicroColdSpray_basic.csv"
      polling_interval: 1.0
      retry:
        delay: 1.0
        max_attempts: 3
      timeout: 5.0
    ssh:
      command_timeout: 2.0
      host: 192.168.0.200
      password: deltatau
      port: 22
      retry:
        delay: 5.0
        max_attempts: 3
      timeout: 5.0
      username: root
  physical:
    hardware_sets:
      set1:
        deagglomerator: deagg1
        feeder: feeder1
        nozzle: nozzle1
        offset_x: 0.0
      set2:
        deagglomerator: deagg2
        feeder: feeder2
        nozzle: nozzle2
        offset_x: 38.1
      deagglomerator:
        speeds:
          off: 35
          low: 30
          medium: 25
          high: 20
      feeder:
        frequency:
          default: 600
          max: 1200
          min: 200
          step: 200
    nozzles:
      common_y: 100.0
      nozzle1_offset_x: 0.0
      nozzle2_offset_x: 38.1
    stage:
      dimensions:
        x: 200.0
        y: 200.0
        z: 40.0
      home:
        x: 0.0
        y: 0.0
        z: 0.0
    substrate_holder:
      dimensions:
        sprayable:
          height: 141.0
          width: 141.0
        total:
          height: 158.14
          width: 158.14
        trough:
          height: 25.4
          offset_y: 16.51
          width: 132.74
  safety:
    gas:
      feeder_flow:
        max: 10.0
        min: 2.0
        warning: 3.0
      feeder_pressure:
        max: 30.8
        min: -15.4
        warning: 16.0
      main_flow:
        max: 100.0
        min: 10.0
        warning: 9.0
      main_pressure:
        max: 130.0
        min: 80.0
        warning: 100.0
      regulator_pressure:
        max: 80.0
        min: 40.0
    motion:
      acceleration_check: true
      limit_check: true
      require_safe_z_for_xy: true
      velocity_check: true
    position:
      tolerance: 0.1
      verification_interval: 1.0
    powder:
      feeder:
        deagglomerator:
          duty_cycle:
            max: 90
            min: 10
          frequency:
            max: 1200
            min: 200
version: 1.0.0
