# Message broker configuration
message_broker:
  # Queue configuration
  queue_size: 1000

  # Topic groups
  topics:
    hardware:
    - hardware/feeder/request
    - hardware/feeder/response
    - hardware/powder/request
    - hardware/powder/response
    - hardware/gas/request
    - hardware/gas/response
    motion:
    - motion/request
    - motion/response
    - motion/status
    file:
    - file/request
    - file/response
    - file/status
    system:
    - system/request
    - system/response
    - system/status
    - system/error
    ui:
    - ui/request
    - ui/response
    - ui/status
    - ui/error
    validation:
    - validation/request
    - validation/response
    - validation/status
    - validation/error
