process:
  action_groups:
    apply_parameters:
      description: Apply parameter set to system
      requires:
      - parameter_file: string
      steps:
      - action: hardware_sets.nozzle_select
        from: '{parameter_file}.nozzle}'
      - action: valves.main_gas_valve
        value: true
      - action: valves.feeder_gas_valve
        value: true
      - action: gas.set_main_flow
        from: '{parameter_file}.main_flow'
      - validation: gas_flow_stable
      - action: gas.set_feeder_flow
        from: '{parameter_file}.feeder_flow'
      - validation: gas_flow_stable
      - action: hardware_sets.deagglomerator_control
        from: '{parameter_file}.deagglomerator'
      - action: hardware_sets.feeder_control
        from: '{parameter_file}.feeder'
      - time_delay: powder_stabilize
    change_parameters:
      description: Change process parameters
      requires:
      - parameter_file: string
      steps:
      - action: gas.set_main_flow
        from: '{parameter_file}.main_flow'
      - validation: gas_flow_stable
      - action: gas.set_feeder_flow
        from: '{parameter_file}.feeder_flow'
      - validation: gas_flow_stable
      - action: hardware_sets.deagglomerator_control
        from: '{parameter_file}.deagglomerator'
      - action: hardware_sets.feeder_control
        from: '{parameter_file}.feeder'
      - time_delay: powder_stabilize
    execute_pattern:
      description: Execute pattern with proper positioning and shutter control
      parameters:
        passes:
          default: 1
          description: Number of pattern passes
          min: 1
          type: integer
      requires:
      - parameter_file: string
      - pattern_file: string
      steps:
      - action_group: move_to_trough
      - action: shutter.control_shutter
        parameters:
          value: true
      - action: motion.move_xy
        from: '{pattern_file}.origin'
      - action: shutter.control_shutter
        parameters:
          value: false
      - repeat:
          count: '{parameters.passes}'
          steps:
          - action: motion.move_xy
            from: '{pattern_file}.moves'
      - action: shutter.control_shutter
        parameters:
          value: true
      - action_group: move_to_trough
    move_to_trough:
      description: Move to trough position
      steps:
      - action: motion.move_z
        parameters:
          z: '{safety.safe_z}'
      - validation: motion_complete
      - action: motion.move_xy
        parameters:
          x: '{hardware.trough.x}'
          y: '{hardware.trough.y}'
      - validation: motion_complete
      - action: motion.move_z
        parameters:
          z: '{hardware.trough.z}'
      - validation: motion_complete
    ready_system:
      description: Prepare system for operation
      steps:
      - action: valves.vent_valve
        value: false
      - action: motion.move_xy
        parameters:
          x: 0
          y: 0
      - action: motion.move_z
        parameters:
          z: 0
      - validation: motion_complete
      - action: valves.gate_valve
        parameters:
          open: false
          partial: true
      - parameters:
          pressure: 200
          timeout: 60.0
        validation: chamber_vacuum
      - action: valves.gate_valve
        parameters:
          open: true
          partial: false
      - parameters:
          pressure: 1.0
          timeout: 120.0
        validation: chamber_vacuum
    shutdown_process:
      description: Shutdown system safely
      steps:
      - action: hardware_sets.feeder_control
        parameters:
          frequency: 0
      - action: hardware_sets.deagglomerator_control
        parameters:
          duty_cycle: 35
      - action: gas.set_feeder_flow
        parameters:
          flow: 0.0
      - action: gas.set_main_flow
        parameters:
          flow: 0.0
      - validation: gas_flow_stable
      - action: valves.feeder_gas_valve
        value: false
      - action: valves.main_gas_valve
        value: false
      - action: motion.move_xy
        parameters:
          x: 0
          y: 0
      - action: motion.move_z
        parameters:
          z: 0
      - validation: motion_complete
      - action: valves.gate_valve
        parameters:
          open: false
          partial: false
      - action: valves.vent_valve
        value: true
    stop_feeder:
      description: Stop powder feed system
      steps:
      - action: hardware_sets.feeder_control
        parameters:
          frequency: 0
      - action: hardware_sets.deagglomerator_control
        parameters:
          duty_cycle: 35
      - action: gas.set_feeder_flow
        parameters:
          flow: 0.0
      - validation: gas_flow_stable
  atomic_actions:
    gas:
      set_feeder_flow:
        description: Set feeder gas flow
        messages:
        - data:
          - tag: gas_control.feeder_flow.setpoint
          topic: tag/set
        validation:
        - tag: gas_control.feeder_flow.measured
      set_main_flow:
        description: Set main gas flow
        messages:
        - data:
          - tag: gas_control.main_flow.setpoint
          topic: tag/set
        validation:
        - tag: gas_control.main_flow.measured
    hardware_sets:
      deagglomerator_control:
        description: Control deagglomerator
        messages:
        - data:
          - tag: hardware_sets.set{1|2}.deagglomerator.duty_cycle
            value: int
          - tag: hardware_sets.set{1|2}.deagglomerator.frequency
            value: int
          topic: tag/set
        validation:
        - tag: hardware_sets.set{1|2}.deagglomerator.duty_cycle
        - tag: hardware_sets.set{1|2}.deagglomerator.frequency
      feeder_control:
        description: Control powder feeder
        messages:
        - data:
          - tag: hardware_sets.set{1|2}.feeder.frequency
            value: int
          topic: tag/set
        validation:
        - tag: hardware_sets.set{1|2}.feeder.frequency
      nozzle_select:
        description: Select active nozzle
        messages:
        - data:
          - tag: hardware_sets.nozzle_select
            value: bool
          topic: tag/set
        validation:
        - tag: hardware_sets.nozzle_select
    motion:
      home_axes:
        description: Reset position tracking to 0,0,0 after manual homing
        messages:
        - data:
          - tag: SetHome
            value: true
          topic: tag/request
        validation:
        - tag: AMC.ModuleStatus
      move_xy:
        description: Coordinated XY move
        messages:
        - data:
          - tag: motion.motion_control.coordinated_move.xy_move.parameters.velocity
          - tag: motion.motion_control.coordinated_move.xy_move.parameters.ramps
          - tag: motion.motion_control.coordinated_move.xy_move.x_position
          - tag: motion.motion_control.coordinated_move.xy_move.y_position
          - tag: motion.motion_control.coordinated_move.xy_move.trigger
          topic: tag/request
        validation:
        - tag: motion.motion_control.coordinated_move.xy_move.status
        - tag: motion.motion_control.coordinated_move.xy_move.in_progress
      move_z:
        description: Z axis move
        messages:
        - data:
          - tag: motion.motion_control.relative_move.z_move.parameters.velocity
          - tag: motion.motion_control.relative_move.z_move.parameters.acceleration
          - tag: motion.motion_control.relative_move.z_move.parameters.deceleration
          - tag: motion.motion_control.relative_move.z_move.trigger
          topic: tag/set
        validation:
        - tag: motion.motion_control.relative_move.z_move.status
        - tag: motion.motion_control.relative_move.z_move.in_progress
    shutter:
      control_shutter:
        description: Control nozzle shutter
        messages:
        - data:
          - tag: relay_control.shutter
            value: bool
          topic: tag/set
        validation:
        - tag: interlocks.shutter_engaged
    vacuum:
      booster_pump:
        description: Control booster pump
        messages:
        - data:
          - tag: vacuum_control.booster_pump.start
            value: bool
          - tag: vacuum_control.booster_pump.stop
            value: bool
          topic: tag/set
        validation:
        - tag: pressure.chamber_pressure
      mechanical_pump:
        description: Control mechanical pump
        messages:
        - data:
          - tag: vacuum_control.mechanical_pump.start
            value: bool
          - tag: vacuum_control.mechanical_pump.stop
            value: bool
          topic: tag/set
        validation:
        - tag: pressure.chamber_pressure
    valves:
      feeder_gas_valve:
        description: Control feeder gas line valve
        messages:
        - data:
          - tag: valve_control.feeder_gas
            value: bool
          topic: tag/set
        validation:
        - tag: valve_control.feeder_gas
      gate_valve:
        description: Control gate valve position
        messages:
        - data:
          - tag: valve_control.gate_valve.partial
            value: bool
          - tag: valve_control.gate_valve.open
            value: bool
          topic: tag/set
        validation:
        - tag: valve_control.gate_valve.partial
        - tag: valve_control.gate_valve.open
      main_gas_valve:
        description: Control main gas line valve
        messages:
        - data:
          - tag: valve_control.main_gas
            value: bool
          topic: tag/set
        validation:
        - tag: valve_control.main_gas
      vent_valve:
        description: Control chamber vent valve
        messages:
        - data:
          - tag: valve_control.vent
            value: bool
          topic: tag/set
        validation:
        - tag: valve_control.vent
  parameters:
    control:
      sequences:
        pattern_execution:
          during_spray:
          - monitor_pressures
          - monitor_flows
          - monitor_position
          - log_process_data
          post_spray:
          - verify_pattern_complete
          - verify_data_logged
          - update_process_history
          pre_spray:
          - verify_chamber_pressure
          - verify_gas_pressures
          - verify_powder_ready
          - verify_position_safe
        startup:
        - verify_vacuum
        - verify_gas_supply
        - verify_powder_level
        - verify_positions_taught
        state_transitions:
          spray_to_wait:
          - verify_in_spraying_state
          - move_to_safe_z
          - move_to_trough
          - stop_powder_feed
          - stop_deagglomerator
          - set_state_wait
          wait_to_shutdown:
          - verify_in_wait_state
          - verify_at_trough
          - move_to_safe_z
          - stop_powder_feed
          - stop_deagglomerator
          - stop_gas_flows
          - move_to_home
          - verify_position
          - set_state_shutdown
          wait_to_spray:
          - verify_in_wait_state
          - verify_at_trough
          - start_powder_feed
          - start_deagglomerator
          - wait_for_powder_stable
          - engage_shutter
          - move_to_safe_z
          - move_to_pattern_start
          - move_to_spray_height
          - disengage_shutter
          - set_state_spraying
      states:
        shutdown:
          requires:
          - PowderFeedOff
          - DeagglomeratorOff
          - GasFlowsOff
          - AtHomePosition
        spraying:
          requires:
          - PowderFeedOn
          - DeagglomeratorOn
          - FlowsStable
          - PressuresStable
        wait:
          requires:
          - PowderFeedOff
          - DeagglomeratorOff
          - AtValidPosition
    environment:
      vacuum:
        chamber:
          pressure:
            error_threshold: 1400.0
            max: 1520.0
            min: 0.01
            sample_period: 1.0
            spray_threshold: 5.0
            warning_threshold: 1000.0
    gas:
      types:
      - flow_control:
          feeder:
            dac_max: 4095
            dac_min: 0
            flow_max: 10.0
            flow_min: 0.0
          main:
            dac_max: 4095
            dac_min: 0
            flow_max: 100.0
            flow_min: 0.0
        name: helium
        scaling_factor: 1.0
      - flow_control:
          feeder:
            dac_max: 4095
            dac_min: 0
            flow_max: 7.2
            flow_min: 0.0
          main:
            dac_max: 4095
            dac_min: 0
            flow_max: 72.0
            flow_min: 0.0
        name: nitrogen
        scaling_factor: 0.72
      - flow_control:
          feeder:
            dac_max: 4095
            dac_min: 0
            flow_max: 8.5
            flow_min: 0.0
          main:
            dac_max: 4095
            dac_min: 0
            flow_max: 85.0
            flow_min: 0.0
        name: argon
        scaling_factor: 0.85
    patterns:
      common_parameters:
        layers:
          default: 1
          description: Number of times to repeat pattern
          min: 1
          type: integer
        origin:
          description: Pattern position relative to holder
          type: vector
          unit: mm
        speed:
          description: Travel speed
          type: float
          unit: mm/s
      types:
        custom:
          parameters:
          - description: Path to CSV file with XY coordinates
            name: path_file
            type: string
        serpentine:
          parameters:
          - description: Pattern length in X direction
            name: length
            type: float
            unit: mm
          - description: Line spacing in Y direction
            name: spacing
            type: float
            unit: mm
          - default: x_first
            description: Primary travel direction
            name: direction
            options:
            - x_first
            - y_first
            type: string
            unit: enum
        spiral:
          parameters:
          - description: Outer diameter of spiral
            name: diameter
            type: float
            unit: mm
          - description: Distance between spiral lines
            name: pitch
            type: float
            unit: mm
  validation:
    hardware:
      active_set:
        message: Selected feeder must match active nozzle
        rule: feeder_matches_nozzle
      set_change:
        message: Must be at trough position to change hardware sets
        rule: at_trough_position
      required_fields:
        message: Missing required hardware set fields
        fields:
        - nozzle
        - feeder
        - deagglomerator
      optional_fields:
        message: Unknown hardware set field
        fields:
        - offset_x
        - notes
    
    parameters:
      material:
        required_fields:
          message: Missing required material fields
          fields:
          - type
          - size
          - manufacturer
          - lot
        optional_fields:
          message: Unknown material field
          fields:
          - notes
          - certifications
      process:
        required_fields:
          message: Missing required process fields
          fields:
          - nozzle
          - chamber
          - gas_flows
          - powder_feed
        optional_fields:
          message: Unknown process field
          fields:
          - notes
          - modifications
      chamber_pressure:
        message: Chamber pressure too high for spraying
        rule: value <= spray_threshold
      feeder_operation:
      - message: Feeder flow too low while running
        rule: not (powder_feed_on and feeder_flow < 2.0)
      flow_stability:
      - message: Main flow not stable
        rule: main_flow_stable
      - message: Feeder flow not stable
        rule: feeder_flow_stable
      - message: Flow rates not stable long enough
        rule: flow_stability_duration >= 5.0
      gas_pressure:
        message: Main gas pressure too low
        rule: main_pressure >= regulator_pressure + min_margin
    
    patterns:
      limits:
        position:
          message: Pattern exceeds sprayable area
          rule: within_sprayable_area
        speed:
          message: Pattern speed exceeds limits
          rule: within_velocity_limits
      serpentine:
        required_fields:
          message: Missing required serpentine pattern fields
          fields:
          - origin
          - length
          - spacing
          - speed
        optional_fields:
          message: Unknown serpentine pattern field
          fields:
          - direction
          - acceleration
      spiral:
        required_fields:
          message: Missing required spiral pattern fields
          fields:
          - origin
          - diameter
          - pitch
          - speed
        optional_fields:
          message: Unknown spiral pattern field
          fields:
          - acceleration
    
    sequences:
      required_fields:
        message: Missing required sequence fields
        fields:
        - metadata
        - steps
      step_fields:
        required_fields:
          message: Missing required step fields
          fields:
          - action
          - parameters
        optional_fields:
          message: Unknown step field
          fields:
          - description
          - timeout
      safe_position:
        message: Must be at safe height before motion
        rule: z_position >= safe_z_height
      spray_conditions:
      - message: Chamber pressure too high for spraying
        rule: chamber_pressure <= spray_threshold
      - message: Gas flows must be stable before spraying
        rule: main_flow_stable and feeder_flow_stable
      max_steps: 100
      types:
        test:
          check_order: true
          required_steps:
          - move
          step_order:
          - move
    
    states:
      chamber_vacuum:
        checks:
        - condition: less_than
          error: Chamber pressure too high for spraying
          tag: pressure.chamber_pressure
          timeout: 30.0
          value: 5.0
          warning: Chamber pressure rising
        description: Verify chamber vacuum
        type: parameters
      feeder_operation:
        checks:
        - condition: greater_than
          error: Feeder flow too low while running
          tag: gas_control.feeder_flow.measured
          timeout: 5.0
          value: 2.0
          warning: Low feeder flow detected
        description: Verify feeder operation
        type: parameters
      gas_flow_stable:
        checks:
        - compare_to: gas_control.main_flow.setpoint
          error: Main gas flow not stable
          tag: gas_control.main_flow.measured
          timeout: 5.0
          tolerance: 2.0
          warning: Main gas flow fluctuating
        - compare_to: gas_control.feeder_flow.setpoint
          error: Feeder flow not stable
          tag: gas_control.feeder_flow.measured
          timeout: 5.0
          tolerance: 0.5
          warning: Flow stability duration < 5.0s
        description: Verify gas flow stability
        type: parameters
      safe_position:
        checks:
        - compare_to: safety.safe_z
          condition: greater_than_equal
          error: Must be at safe height before motion
          tag: motion.position.z_position
          warning: Z position near minimum safe height
        description: Verify safe position
        type: sequence
    
    time_delays:
      powder_stabilize:
        delay: 5.0
        description: Wait for powder flow to stabilize
      shutter_motion:
        delay: 0.5
        description: Wait for shutter to complete motion
