version: "1.0.0"
process:
  # 1. Process Parameters
  parameters:
    # 1. Gas Control
    gas:
      types:
        - name: "helium"
          scaling_factor: 1.0
          flow_control:
            main:
              dac_min: 0
              dac_max: 4095
              flow_min: 0.0
              flow_max: 100.0
            feeder:
              dac_min: 0
              dac_max: 4095
              flow_min: 0.0
              flow_max: 10.0
        - name: "nitrogen"
          scaling_factor: 0.72
          flow_control:
            main:
              dac_min: 0
              dac_max: 4095
              flow_min: 0.0
              flow_max: 72.0
            feeder:
              dac_min: 0
              dac_max: 4095
              flow_min: 0.0
              flow_max: 7.2
        - name: "argon"
          scaling_factor: 0.85
          flow_control:
            main:
              dac_min: 0
              dac_max: 4095
              flow_min: 0.0
              flow_max: 85.0
            feeder:
              dac_min: 0
              dac_max: 4095
              flow_min: 0.0
              flow_max: 8.5

    # 2. Powder System
    powder:
      feeders:
        active_set: "set1"  # Default to set 1
        set1:
          frequency:
            min: 200
            max: 1200
            step: 200
            default: 600
          deagglomerator:
            duty_cycle:
              min: 0
              max: 100
              default: 35
            frequency:
              default: 500
        set2:
          frequency:
            min: 200
            max: 1200
            step: 200
            default: 600
          deagglomerator:
            duty_cycle:
              min: 0
              max: 100
              default: 35
            frequency:
              default: 500

    # 3. Process Environment
    environment:
      vacuum:
        chamber:
          pressure:
            min: 0.01
            max: 1520.0
            spray_threshold: 5.0
            warning_threshold: 1000.0
            error_threshold: 1400.0
            sample_period: 1.0

    # 4. Motion Patterns
    patterns:
      common_parameters:  # Shared across all patterns
        speed:
          type: "float"
          unit: "mm/s"
          description: "Travel speed"
        layers:
          type: "integer"
          min: 1
          default: 1
          description: "Number of times to repeat pattern"
        origin:
          type: "vector"
          unit: "mm"
          description: "Pattern position relative to holder"

      types:
        serpentine:
          parameters:
            - name: "length"
              type: "float"
              unit: "mm"
              description: "Pattern length in X direction"
            - name: "spacing"
              type: "float"
              unit: "mm"
              description: "Line spacing in Y direction"
            - name: "direction"
              type: "string"
              unit: "enum"
              options: ["x_first", "y_first"]
              default: "x_first"
              description: "Primary travel direction"
      
        spiral:
          parameters:
            - name: "diameter"
              type: "float"
              unit: "mm"
              description: "Outer diameter of spiral"
            - name: "pitch"
              type: "float"
              unit: "mm"
              description: "Distance between spiral lines"
      
        custom:
          parameters:
            - name: "path_file"
              type: "string"
              description: "Path to CSV file with XY coordinates"

    # 5. Process Control
    control:
      sequences:
        startup:
          - verify_vacuum
          - verify_gas_supply
          - verify_powder_level
          - verify_positions_taught
      
        pattern_execution:
          pre_spray:
            - verify_chamber_pressure
            - verify_gas_pressures
            - verify_powder_ready
            - verify_position_safe
          during_spray:
            - monitor_pressures
            - monitor_flows
            - monitor_position
            - log_process_data
          post_spray:
            - verify_pattern_complete
            - verify_data_logged
            - update_process_history
      
        state_transitions:
          wait_to_spray:
            - verify_in_wait_state
            - verify_at_trough
            - start_powder_feed
            - start_deagglomerator
            - wait_for_powder_stable
            - engage_shutter
            - move_to_safe_z
            - move_to_pattern_start
            - move_to_spray_height
            - disengage_shutter
            - set_state_spraying
          spray_to_wait:
            - verify_in_spraying_state
            - move_to_safe_z
            - move_to_trough
            - stop_powder_feed
            - stop_deagglomerator
            - set_state_wait
          wait_to_shutdown:
            - verify_in_wait_state
            - verify_at_trough
            - move_to_safe_z
            - stop_powder_feed
            - stop_deagglomerator
            - stop_gas_flows
            - move_to_home
            - verify_position
            - set_state_shutdown

      states:
        wait:
          requires:
            - "PowderFeedOff"
            - "DeagglomeratorOff"
            - "AtValidPosition"
        spraying:
          requires:
            - "PowderFeedOn"
            - "DeagglomeratorOn"
            - "FlowsStable"
            - "PressuresStable"
        shutdown:
          requires:
            - "PowderFeedOff"
            - "DeagglomeratorOff"
            - "GasFlowsOff"
            - "AtHomePosition"

  # 2. Validation Rules
  validation:
    process_parameters:
      chamber_pressure:
        rule: "value <= spray_threshold"
        message: "Chamber pressure too high for spraying"
      gas_pressure:
        rule: "main_pressure >= regulator_pressure + min_margin"
        message: "Main gas pressure too low"
      feeder_operation:
        - rule: "not (powder_feed_on and feeder_flow < 2.0)"
          message: "Feeder flow too low while running"
      flow_stability:
        - rule: "main_flow_stable"
          message: "Main flow not stable"
        - rule: "feeder_flow_stable"
          message: "Feeder flow not stable"
        - rule: "flow_stability_duration >= 5.0"
          message: "Flow rates not stable long enough"

    pattern_limits:
      position:
        rule: "within_sprayable_area"
        message: "Pattern exceeds sprayable area"
      speed:
        rule: "within_velocity_limits"
        message: "Pattern speed exceeds limits"

    sequence_rules:
      validation:
        max_steps: 100
        types:
          test:
            required_steps: ['move']
            check_order: true
            step_order: ['move']
      safe_position:
        rule: "z_position >= safe_z_height"
        message: "Must be at safe height before motion"
      spray_conditions:
        - rule: "chamber_pressure <= spray_threshold"
          message: "Chamber pressure too high for spraying"
        - rule: "main_flow_stable and feeder_flow_stable"
          message: "Gas flows must be stable before spraying"

    hardware_sets:
      active_set:
        rule: "feeder_matches_nozzle"
        message: "Selected feeder must match active nozzle"
      set_change:
        rule: "at_trough_position"
        message: "Must be at trough position to change hardware sets"

  # 3. Safety Rules
  safety:
    interlocks:
      # Define only the interlocks you actually have
      # Example:
      # emergency_stop: "EmergencyStop"
      # pressure_ok: "PressureOK"
    
    limits:
      # Define any safety limits you need to monitor
      # Example:
      # pressure:
      #   tag: "SystemPressure"
      #   min: 0.0
      #   max: 100.0
      # temperature:
      #   tag: "SystemTemperature"
      #   min: 10.0
      #   max: 50.0