version: "1.0.0"
state:
  # State Transitions (simplified)
  transitions:
    system:
      INITIALIZING: ["READY", "ERROR"]
      READY: ["RUNNING", "ERROR", "SHUTDOWN"]
      RUNNING: ["PAUSED", "ERROR"]
      PAUSED: ["RUNNING", "ERROR", "SHUTDOWN"]
      ERROR: ["READY", "SHUTDOWN"]
      SHUTDOWN: []

    connection:
      DISCONNECTED: ["CONNECTING"]
      CONNECTING: ["CONNECTED", "ERROR"]
      CONNECTED: ["DISCONNECTED", "ERROR"]
      ERROR: ["DISCONNECTED"]

    motion:
      DISABLED: ["HOMING"]
      HOMING: ["READY", "ERROR"]
      READY: ["MOVING", "DISABLED", "ERROR"]
      MOVING: ["READY", "ERROR"]
      ERROR: ["DISABLED"]

    process:
      IDLE: ["PREPARING", "ERROR"]
      PREPARING: ["SPRAYING", "ERROR"]
      SPRAYING: ["STOPPING", "ERROR"]
      STOPPING: ["IDLE", "ERROR"]
      ERROR: ["IDLE"]

  # Error Handling (simplified)
  errors:
    retry:
      max_attempts: 3
      delay: 5.0
    
    categories:
      hardware:
        - motion
        - plc
        - ssh
      process:
        - vacuum
        - gas

  # State Monitoring
  monitoring:
    update_rate: 100  # ms
    history_length: 1000
    state_change_logging: true

  # Messaging Topics (removed safety-related topics)
  messaging:
    topics:
      system:
        - state/change
        - state/error
        - system/shutdown
        - system/initialize
      hardware:
        - hardware/status 
        - hardware/error
        - hardware/connect
        - hardware/disconnect
      motion:
        - motion/status
        - motion/error
        - motion/home
        - motion/move
        - motion/stop
      process:
        - process/status
        - process/error
        - process/start
        - process/stop
        - process/pause
        - process/resume
      sequence:
        - sequence/load
        - sequence/start
        - sequence/stop
        - sequence/pause
        - sequence/resume
        - sequence/complete
        - sequence/error
      parameters:
        - parameters/load
        - parameters/save
        - parameters/validate
        - parameters/apply
        - parameters/error