state:
  transitions:
    ERROR:
      next_states:
      - READY
      - SHUTDOWN
    INITIALIZING:
      conditions:
      - hardware.connected
      - config.loaded
      next_states:
      - READY
    READY:
      conditions:
      - hardware.connected
      - hardware.enabled
      next_states:
      - RUNNING
      - SHUTDOWN
    RUNNING:
      conditions:
      - hardware.connected
      - hardware.enabled
      - sequence.active
      next_states:
      - READY
      - ERROR
    SHUTDOWN:
      conditions:
      - hardware.safe
      next_states:
      - INITIALIZING
version: 1.0.0
