version: "1.0.0"
state:
  transitions:
    INITIALIZING:
      next_states: ["READY"]
      conditions:
        - "hardware.connected"
        - "config.loaded"
      
    READY:
      next_states: ["RUNNING", "SHUTDOWN"]
      conditions:
        - "hardware.connected"
        - "hardware.enabled"
      
    RUNNING:
      next_states: ["READY", "ERROR"]
      conditions:
        - "hardware.connected"
        - "hardware.enabled"
        - "sequence.active"
      
    ERROR:
      next_states: ["READY", "SHUTDOWN"]
      
    SHUTDOWN:
      next_states: ["INITIALIZING"]
      conditions:
        - "hardware.safe"