state:
  transitions:
    system:
      ERROR:
      - INITIALIZING
      INITIALIZING:
      - READY
      - ERROR
      READY:
      - RUNNING
      - ERROR
      RUNNING:
      - STOPPED
      - ERROR
      STOPPED:
      - READY
      - ERROR
